// --------TASK1---------
console.log("11%2=" + 11 % 2);
console.log("36%3=" + 36 % 3);
console.log("'5'+5=" + "5" + 5);
console.log("'Hello'+ 5=" + "Hello" + 5);
var a = 0;
console.log("a=" + a);
++a;
console.log("++a=" + a);
++a;
console.log("++a=" + a);
++a;
console.log("++a=" + a);
a = 0;
console.log("a=" + a);
a++;
console.log("a++=" + a);
a++;
console.log("a++=" + a);
a++;
console.log("a++=" + a);